name: Linter check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Linter check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create example .env file
        run: cat '.example.env' > .env

      - name: Installing deps
        run: npm i

      - name: Run linter
        run: npm run lint
