name: Type check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Installing deps
        run: npm i

      - name: Run type check
        run: npm run type-check
